"""add osm_id and monument_images

Revision ID: 7fb4e652a6cf
Revises: 
Create Date: 2026-04-08 11:15:34.966382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb4e652a6cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monument_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('monument_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['monument_id'], ['monuments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('monuments', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('monuments', sa.Column('osm_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_monuments_osm_id'), 'monuments', ['osm_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monuments_osm_id'), table_name='monuments')
    op.drop_column('monuments', 'osm_id')
    op.drop_column('monuments', 'category')
    op.drop_table('monument_images')
    # ### end Alembic commands ###
